language: node_js

node_js:
  - "4.0"

sudo: false

install:
- npm install
- npm install -g grunt-cli
- npm install -g npm@'>=2.13.5'

env:
  global:
  - GH_REF: github.com/ScottLogic/d3fc.git
  - secure: "dimY26/YND+hamNAH6lwjYqkmc4qEkSDPl8xwe7wJxliR8k8cPM8lRw8c/Iwtmq3NiG5cZoiKAkALA4PTl3zQ7YOj7rSL9pGmi4qJvtObqWljclJjY/0sNprPc/RrRTgpBcnI3Pa7fofiT2uLNp+a0mT/KV9KZNxjQIw8PA2RkY="
  - secure: "P0k9RiBmmEd9b6nnP1SVKmt6nu8qpzPr62dA2x33PJ+IyTYlDS63RrowpWBihOzcqufJ9rL1m5e7lsHwMvXKiX4iYrZSeSsqXuFmpr2DhxQe/TRW6joadkK6fLn0j7TGa+fA3z0pecxu8yG9YJYqlQcjjEAl2ppgn0fIPuXLY3I="
  - secure: "frnRQCKJjvouehihdCv/j0cKxtiOjUn3b0y/a7PYmyU/UZNP6FXya8y1pp7+7LsAWpnsK7oFKvZ5QoUVtloRO0wDHcAuetoF1BVEybcuYYkJPnMDSzm3+oiCDi6IaQgOfC2c5xcU0QHz4zqi8wHvyBuPJQ28VdhlRlX7DY5FjEI="

after_success: bash ./site/deploy.sh

deploy:
  - provider: npm
    email: price.c@gmail.com
    api_key:
      secure: "A0JeRqeOUJXxMuwVUlJ0JqrmWB+RbuECIQ6dEJoDaeQEKatUKP3uVtTn0sO1xyvHBUtkS2ImnnOjIJ2XGcnACjoPU58/E88ICcTOBhTBfplHi78e/mYTYIM7o3VOTWud+3aAsfw7O7YrmOLnhe1Dm65TQKxXH9EfoYLIbta7+9Q="
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "anji1SlRHf9kXmQ4M1L0/Y3s+vXtvDuKKk02VBsWPcIBDFPcSmK+C9DBRAKUq6953C1cImUf/GvKlh1zHKkiLz0mG0zoovufrflThk2rxQqnIJ9Ec6Igmh5us32DVxEcTNyXBJFNeHsMB1Wg5PkOffYbEr+e+wxgoCQKpDXMR7k="
    file:
      - "dist/d3fc.css"
      - "dist/d3fc.js"
      - "dist/d3fc.min.css"
      - "dist/d3fc.min.js"
      - "dist/d3fc.min.js.map"
      - "dist/d3fc.bundle.js"
      - "dist/d3fc.bundle.min.js"
      - "dist/d3fc.bundle.min.js.map"
    skip_cleanup: true
    on:
      branch: master
      tags: true
